@startuml
!theme toy

top to bottom direction

package "com.example.starlet_be.swagger" {

    class SwaggerConfig << (C,#FFDDAA) Configuration >> {
        --
        + openApi(): GroupedOpenApi (@Bean)
    }

    class GroupedOpenApi

    annotation OpenAPIDefinition
    annotation SecurityScheme

    SwaggerConfig .down.> GroupedOpenApi : creates/returns Bean

    SwaggerConfig ..|> OpenAPIDefinition : annotates
    SwaggerConfig ..|> SecurityScheme : annotates
}
@enduml